#!/bin/bash

if [ -z $1 ]; then
     echo write filename
     exit 1
else
     OUTPUT_FILE_NAME_STRING=`cat ./$1 | grep "//#build-name" -m 1`
     
     if [ $? -eq 0 ]; then
        
        OUTPUT_FILE_NAME_WITH_WHITESPACE=${OUTPUT_FILE_NAME_STRING#*//#build-name}
        OUTPUT_FILE_NAME=`echo $OUTPUT_FILE_NAME_WITH_WHITESPACE | tr -d '[:space:]'`
        
        if [ -z $OUTPUT_FILE_NAME ]; then
            echo enter valid output filename in source file
            exit 1
           
        else
            TEMPFOLDER_PATH=`mktemp -d`
            
            trap "rm -Rf $TEMPFOLDER_PATH; exit 1" KILL INT HUP TERM

            cp $1 $TEMPFOLDER_PATH/
            
            CURRENT_DIR=$(pwd)
            
            cd $TEMPFOLDER_PATH
            
            gcc $1 -o $OUTPUT_FILE_NAME
            
            if [ $? -eq 0 ]; then
            
            mv $OUTPUT_FILE_NAME "$CURRENT_DIR"
            
            cd "$CURRENT_DIR"
            
            rm -Rf $TEMPFOLDER_PATH
            
            echo success build file is $OUTPUT_FILE_NAME
            
            else
                echo failed
                cd "$CURRENT_DIR"
                rm -Rf $TEMPFOLDER_PATH
                exit 1
            fi
        fi
        
    else
        echo 'enter existing file name or write //#build-name - in file content' 
        exit 1
    fi
fi
exit 0
